### PR TITLE
Documention fixes

### LINKED ISSUE #52: filestore error: file does not exist
I see a bunch of lines in the log that look like this

```time="2019-06-18T16:26:06Z" level=warning msg="filestore error: file does not exist" source="server.go:478"
time="2019-06-18T16:26:23Z" level=warning msg="filestore error: file does not exist" source="server.go:478"
time="2019-06-18T16:51:17Z" level=warning msg="filestore error: file does not exist" source="server.go:478"
time="2019-06-18T17:13:30Z" level=warning msg="filestore error: file does not exist" source="server.go:478"
time="2019-06-18T17:20:13Z" level=warning msg="filestore error: file does not exist" source="server.go:478"
time="2019-06-18T17:44:11Z" level=warning msg="filestore error: file does not exist" source="server.go:478"
time="2019-06-18T17:44:54Z" level=warning msg="filestore error: file does not exist" source="server.go:478"```

Would be good to know which file doesn't exist and/or suppress this warning.

### LINKED ISSUE #53: Add readme for http/notifier and notifier

### LINKED ISSUE #54: Add "scale" attribute to grids/providers/postgres example.
`scale` is required now so it should be part of the example.

### LINKED ISSUE #56: [server] document /jobs/{job_id}/status endpoints

### LINKED ISSUE #57: [coordinator] readme shows config block with array syntax when it should be object syntax
`[[webserver.coordinator]]` should be `[webserver.coordinator]`

### LINKED ISSUE #62: Unnecessary database log being printed for no rows found
```
time="2019-06-28T22:03:31Z" level=warning msg="got error finding job F701G17773-0-50k: no rows in result set -- \n\nSELECT \n    job.id,\n    job.queue_id,\n    job.created as enqueued,\n    jobstatus.status,\n    jobstatus.description,\n    jobstatus.created as updated\nFROM jobs AS job\nJOIN statuses AS jobstatus ON job.id = jobstatus.job_id\nWHERE job.mdgid = $1 AND job.sheet_number = $2 AND job.sheet_name = $3\nORDER BY jobstatus.id desc limit 1;\n\t" source="postgresql.go:418"
```

### LINKED ISSUE #65: [config] sheet width and height not documented

### PR DESCRIPTION
**Pull request by gdey**
Various fixes for documentation and documentation related issues.

fixes #52 
fixes #53 
fixes #54 
fixes #56 
fixes #57 
fixes #62 
fixes #65

### CODE REVIEW

File: atlante/config/config_test.go [hunk 1]
```diff
@@ -4,4 +4,22 @@ import "testing"
...
 
+	type tcase struct {
+		file   string // This name of the file to load from the testdata directory
+		Err    error  // expected error
+		config Config // Expected Config
+	}
+
+	fn := func(tc tcase) (string, func(*testing.T)) {
+		return tc.file, func(t *testing.T) {
+			//...
```
Comment (ARolek) [inline atlante/config/config_test.go]: any reason this test is stubbed out but not implemented?

File: atlante/grids/postgresql/postgresql.go [hunk 2]
```diff
@@ -176,6 +177,12 @@ func NewGridProvider(config grids.ProviderConfig) (grids.Provider, error) {
 	queryLngLat, _ = config.String(ConfigKeyQueryLngLat, &queryLngLat)
 	var queryMDGID string
 	queryMDGID, _ = config.String(ConfigKeyQueryMDGID, &queryMDGID)
+	if (queryLngLat != "" || queryMDGID != "") && (queryLngLat == "" || queryMDGID == "") {
+		if queryLngLat == "" {
+			return nil, errors.String("error " + ConfigKeyQueryLngLat + " not set, when " + ConfigKeyQueryMDGID + " is set")
```
Comment (ARolek) [inline atlante/grids/postgresql/postgresql.go]: maybe `errors` needs something similar to fmt.Errorf(...)?

File: atlante/internal/urlutil/urlutil.go [hunk 3]
```diff
@@ -12,38 +12,48 @@ import (
...
+// ErrFileNotExists is returned when the requested local file is not found
 type ErrFileNotExists ErrFile
 
+// Error implements the error interface
 func (e ErrFileNotExists) Error() string {
 	return fmt.Sprintf("file at location (%v) not found!", e.Filename)
 }
 
+// ReaderCloser is an io.Reader with a close method
 type ReaderCloser interface {
```
Comment (ARolek) [inline atlante/internal/urlutil/urlutil.go]: Why not use the native io.ReadCloser interface? https://golang.org/pkg/io/#ReadCloser

File: atlante/server/README.md [hunk 4]
```diff
@@ -71,3 +101,67 @@ Returns:
    "status" : "requested" | "started" | "processing" | "completed",
 }
 ```
+
+5. `GET /jobs` will return the latest 100 jobs
```
Comment (ARolek) [inline atlante/server/README.md]: I recall looking at the code and the limit value can be passed in. Is this correct?

File: atlante/grids/postgresql/postgresql.go (hunk 2 above)
Comment (gdey) [reply atlante/grids/postgresql/postgresql.go]: There is a reason I did it this way. This will generate a constant string, instead of a string that has to be interpolated.

File: atlante/internal/urlutil/urlutil.go (hunk 3 above)
Comment (gdey) [reply atlante/internal/urlutil/urlutil.go]: I think I just did not see it when I looked. I remember being confused that there wasn't one...

File: atlante/server/README.md (hunk 4 above)
Comment (gdey) [reply atlante/server/README.md]: No it's hard coded right now.
